/**
 * Recurring expense helpers: auto-post due payments (Spotify, internet, etc.)
 * and detect whether an occurrence is already on the ledger.
 */

import { startOfMonth } from "date-fns";
import { prisma } from "@/lib/db";
import { todayISO } from "@/lib/utils";
import {
  monthsFromOffset,
  recurringOccurrenceDate,
} from "@/lib/recurring-income";

export async function recurringExpenseOccurrenceHandled(opts: {
  householdId: string;
  date: string;
  amountCents: number;
  description: string;
  accountId?: string | null;
  creditCardId?: string | null;
}): Promise<boolean> {
  const { householdId, date, amountCents, description, accountId, creditCardId } =
    opts;

  const dismissed = await prisma.transaction.findFirst({
    where: {
      householdId,
      type: "expense",
      date,
      amountCents,
      description,
      isAutoGenerated: true,
      deletedAt: { not: null },
    },
    select: { id: true },
  });
  if (dismissed) return true;

  const live = await prisma.transaction.findFirst({
    where: {
      householdId,
      deletedAt: null,
      type: "expense",
      date,
      amountCents,
      description,
      OR: [
        ...(accountId
          ? [
              { accountId },
              { fundings: { some: { accountId } } },
            ]
          : []),
        ...(creditCardId
          ? [
              { creditCardId },
              { fundings: { some: { creditCardId } } },
            ]
          : []),
        ...(!accountId && !creditCardId ? [{ id: { not: "" } }] : []),
      ],
    },
    select: { id: true },
  });
  return Boolean(live);
}

export async function ensureRecurringExpensesPosted(
  householdId: string,
  opts?: { monthsBack?: number; userId?: string | null }
): Promise<{ created: number }> {
  const monthsBack = opts?.monthsBack ?? 3;
  const today = todayISO();
  const base = startOfMonth(new Date());

  const recurring = await prisma.recurringExpense.findMany({
    where: { householdId, active: true },
  });
  if (!recurring.length) return { created: 0 };

  const defaultAccount =
    (await prisma.account.findFirst({
      where: { householdId, ownerUserId: null },
      orderBy: { createdAt: "asc" },
    })) ||
    (await prisma.account.findFirst({
      where: { householdId },
      orderBy: { createdAt: "asc" },
    }));

  let created = 0;

  for (const r of recurring) {
    const creditCardId = r.creditCardId || null;
    const accountId = creditCardId ? null : r.accountId || defaultAccount?.id || null;
    if (!accountId && !creditCardId) continue;

    const createdAt = r.createdAt instanceof Date ? r.createdAt : new Date(r.createdAt);
    const ruleStart = `${createdAt.getFullYear()}-${String(createdAt.getMonth() + 1).padStart(2, "0")}-01`;

    for (let i = -monthsBack; i <= 0; i++) {
      const { year, month } = monthsFromOffset(base, i);
      const dateStr = recurringOccurrenceDate(year, month, r.dayOfMonth);
      if (dateStr > today) continue;
      if (dateStr < ruleStart) continue;

      const handled = await recurringExpenseOccurrenceHandled({
        householdId,
        date: dateStr,
        amountCents: r.amountCents,
        description: r.description,
        accountId,
        creditCardId,
      });
      if (handled) continue;

      await prisma.transaction.create({
        data: {
          householdId,
          date: dateStr,
          amountCents: r.amountCents,
          description: r.description,
          type: "expense",
          categoryId: r.categoryId,
          accountId,
          creditCardId,
          isAutoGenerated: true,
          createdById: opts?.userId || null,
          fundings: {
            create: {
              amountCents: r.amountCents,
              accountId,
              creditCardId,
            },
          },
        },
      });
      created++;
    }
  }

  return { created };
}
