/**
 * Recurring income helpers: calendar occurrence dates + auto-post due payments
 * so end-of-month salaries (e.g. day 30) still land when you open the app later.
 */

import { addMonths, startOfMonth } from "date-fns";
import { prisma } from "@/lib/db";
import { todayISO } from "@/lib/utils";
import { clampDay } from "@/lib/credit-card-cycles";

/** YYYY-MM-DD for dayOfMonth in a given calendar month (clamps 31 → 28/29/30). */
export function recurringOccurrenceDate(
  year: number,
  month1to12: number,
  dayOfMonth: number
): string {
  const day = clampDay(year, month1to12, dayOfMonth);
  return `${year}-${String(month1to12).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

export function monthsFromOffset(base: Date, offset: number): {
  year: number;
  month: number;
} {
  const d = addMonths(startOfMonth(base), offset);
  return { year: d.getFullYear(), month: d.getMonth() + 1 };
}

/**
 * Create real income transactions for recurring items whose pay date is on or
 * before today and not already recorded (auto or manual match).
 *
 * Looks back a few months so opening the app on the 1st still captures
 * last month’s day-28/29/30/31 salary.
 */
export async function ensureRecurringIncomesPosted(
  householdId: string,
  opts?: { monthsBack?: number; userId?: string | null }
): Promise<{ created: number }> {
  const monthsBack = opts?.monthsBack ?? 3;
  const today = todayISO();
  const base = startOfMonth(new Date());

  const recurring = await prisma.recurringIncome.findMany({
    where: { householdId, active: true },
  });
  if (!recurring.length) return { created: 0 };

  const defaultAccount =
    (await prisma.account.findFirst({
      where: { householdId, ownerUserId: null },
      orderBy: { createdAt: "asc" },
    })) ||
    (await prisma.account.findFirst({
      where: { householdId },
      orderBy: { createdAt: "asc" },
    }));

  let created = 0;

  for (const r of recurring) {
    const accountId = r.accountId || defaultAccount?.id || null;
    if (!accountId) continue;

    // Don't invent paydays before this rule existed (use start of its creation month)
    const createdAt = r.createdAt instanceof Date ? r.createdAt : new Date(r.createdAt);
    const ruleStart = `${createdAt.getFullYear()}-${String(createdAt.getMonth() + 1).padStart(2, "0")}-01`;

    for (let i = -monthsBack; i <= 0; i++) {
      const { year, month } = monthsFromOffset(base, i);
      const dateStr = recurringOccurrenceDate(year, month, r.dayOfMonth);
      if (dateStr > today) continue;
      if (dateStr < ruleStart) continue;

      const already = await prisma.transaction.findFirst({
        where: {
          householdId,
          deletedAt: null,
          type: "income",
          date: dateStr,
          amountCents: r.amountCents,
          accountId,
          OR: [
            { isAutoGenerated: true, description: r.description },
            { description: r.description },
          ],
        },
        select: { id: true },
      });
      if (already) continue;

      await prisma.transaction.create({
        data: {
          householdId,
          date: dateStr,
          amountCents: r.amountCents,
          description: r.description,
          type: "income",
          categoryId: r.categoryId,
          accountId,
          isAutoGenerated: true,
          createdById: opts?.userId || null,
        },
      });
      created++;
    }
  }

  return { created };
}

/** Build future (today+) occurrence dates for a recurring income within a horizon. */
export function listFutureRecurringDates(opts: {
  dayOfMonth: number;
  fromDate: string; // YYYY-MM-DD inclusive
  untilDate: string;
  monthsAhead?: number;
}): string[] {
  const monthsAhead = opts.monthsAhead ?? 14;
  const base = startOfMonth(new Date(opts.fromDate + "T12:00:00"));
  const out: string[] = [];
  for (let i = 0; i < monthsAhead; i++) {
    const { year, month } = monthsFromOffset(base, i);
    const dateStr = recurringOccurrenceDate(year, month, opts.dayOfMonth);
    if (dateStr < opts.fromDate) continue;
    if (dateStr > opts.untilDate) break;
    out.push(dateStr);
  }
  return out;
}
