export const DEFAULT_CATEGORIES = [
  { name: "Alimentación", type: "expense", icon: "🍽️", color: "#f97316" },
  { name: "Transporte", type: "expense", icon: "🚗", color: "#3b82f6" },
  { name: "Vivienda", type: "expense", icon: "🏠", color: "#8b5cf6" },
  { name: "Entretenimiento", type: "expense", icon: "🎬", color: "#ec4899" },
  { name: "Salud", type: "expense", icon: "🏥", color: "#ef4444" },
  { name: "Educación", type: "expense", icon: "📚", color: "#14b8a6" },
  { name: "Ropa", type: "expense", icon: "👕", color: "#a855f7" },
  { name: "Servicios", type: "expense", icon: "📱", color: "#06b6d4" },
  { name: "Otros gastos", type: "expense", icon: "📦", color: "#64748b" },
  { name: "Salario", type: "income", icon: "💰", color: "#22c55e" },
  { name: "Freelance", type: "income", icon: "💻", color: "#84cc16" },
  { name: "Inversiones", type: "income", icon: "📈", color: "#10b981" },
  { name: "Otros ingresos", type: "income", icon: "🎁", color: "#34d399" },
] as const;

export const DEFAULT_ACCOUNTS = [
  { name: "Efectivo", type: "cash", icon: "💵" },
  { name: "Cuenta de cheques", type: "checking", icon: "🏦" },
  { name: "Tarjeta de débito", type: "debit", icon: "💳" },
] as const;

/** Keyword auto-categorization (lowercase keys → category name) */
export const CATEGORY_KEYWORDS: Record<string, string> = {
  // food / groceries
  oxxo: "Alimentación",
  walmart: "Alimentación",
  soriana: "Alimentación",
  abarrotes: "Alimentación",
  super: "Alimentación",
  coca: "Alimentación",
  pepsi: "Alimentación",
  pan: "Alimentación",
  bimbo: "Alimentación",
  leche: "Alimentación",
  huevo: "Alimentación",
  tortilla: "Alimentación",
  carne: "Alimentación",
  pollo: "Alimentación",
  fruta: "Alimentación",
  verdura: "Alimentación",
  cafe: "Alimentación",
  café: "Alimentación",
  pizza: "Alimentación",
  hamburguesa: "Alimentación",
  taco: "Alimentación",
  restaurant: "Alimentación",
  restaurante: "Alimentación",
  starbucks: "Alimentación",
  sabritas: "Alimentación",
  galleta: "Alimentación",
  yogurt: "Alimentación",
  queso: "Alimentación",
  arroz: "Alimentación",
  frijol: "Alimentación",
  agua: "Alimentación",
  jugo: "Alimentación",
  cerveza: "Alimentación",
  vino: "Alimentación",
  // transport
  uber: "Transporte",
  didi: "Transporte",
  gasolina: "Transporte",
  pemex: "Transporte",
  "total energies": "Transporte",
  metro: "Transporte",
  estacionamiento: "Transporte",
  parking: "Transporte",
  peaje: "Transporte",
  caseta: "Transporte",
  taxi: "Transporte",
  // housing
  renta: "Vivienda",
  hipoteca: "Vivienda",
  predial: "Vivienda",
  // services
  cfe: "Servicios",
  totalplay: "Servicios",
  "total play": "Servicios",
  telcel: "Servicios",
  izzi: "Servicios",
  megacable: "Servicios",
  internet: "Servicios",
  "recibo de agua": "Servicios",
  "servicio de agua": "Servicios",
  luz: "Servicios",
  "gas natural": "Servicios",
  "gas lp": "Servicios",
  // entertainment
  netflix: "Entretenimiento",
  spotify: "Entretenimiento",
  cine: "Entretenimiento",
  disney: "Entretenimiento",
  steam: "Entretenimiento",
  xbox: "Entretenimiento",
  playstation: "Entretenimiento",
  juego: "Entretenimiento",
  // health
  farmacia: "Salud",
  hospital: "Salud",
  medico: "Salud",
  médico: "Salud",
  medicina: "Salud",
  doctor: "Salud",
  dental: "Salud",
  // education
  escuela: "Educación",
  universidad: "Educación",
  libro: "Educación",
  curso: "Educación",
  // clothing
  ropa: "Ropa",
  zapato: "Ropa",
  zara: "Ropa",
  nike: "Ropa",
  adidas: "Ropa",
  // income
  nomina: "Salario",
  nómina: "Salario",
  sueldo: "Salario",
  salario: "Salario",
};
