import { z } from "zod";
import {
  ForbiddenError,
  requireHouseholdAccess,
  requireSession,
} from "@/lib/auth";
import { prisma } from "@/lib/db";
import { jsonError, jsonOk } from "@/lib/access";
import { pesosToCents, todayISO } from "@/lib/utils";
import { logActivity } from "@/lib/household";
import { canSeeModule, filterAccountId } from "@/lib/visibility";

/**
 * Manual credit-card payment. Never auto-created — user must press Pay.
 * Drains a bank/cash account and reduces remaining statement dues.
 */
export async function POST(
  req: Request,
  ctx: { params: Promise<{ id: string }> }
) {
  try {
    const session = await requireSession();
    const m = await requireHouseholdAccess(session.userId, { write: true });
    if (!canSeeModule(m.visibility, "creditCards")) {
      throw new ForbiddenError("No access to credit cards");
    }
    const { id } = await ctx.params;
    if (m.visibility.hiddenCreditCardIds.includes(id)) {
      throw new ForbiddenError("No access to this card");
    }

    const raw = await req.json();
    const { extractIdempotencyKey, withIdempotency } = await import(
      "@/lib/idempotency"
    );
    const idemKey = extractIdempotencyKey(req, raw);

    return withIdempotency(
      {
        userId: session.userId,
        path: `/api/credit-cards/${id}/pay`,
        key: idemKey,
      },
      async () => {
        const body = z
          .object({
            accountId: z.string().min(1),
            amount: z.union([z.number(), z.string()]),
            date: z.string().optional(),
            cycleDue: z.string().optional().nullable(),
            description: z.string().optional(),
          })
          .parse(raw);

        const card = await prisma.creditCard.findFirst({
          where: { id, householdId: m.householdId },
        });
        if (!card) throw new Error("Tarjeta no encontrada");

        const account = await prisma.account.findFirst({
          where: { id: body.accountId, householdId: m.householdId },
        });
        if (!account) throw new Error("Cuenta no encontrada");
        if (!filterAccountId(m.visibility, account.id)) {
          throw new ForbiddenError("No access to this account");
        }

        const amountCents = pesosToCents(body.amount);
        if (amountCents <= 0) throw new Error("Monto inválido");

        const date = body.date || todayISO();
        const description =
          (body.description && body.description.trim()) ||
          `Pago tarjeta ${card.name}`;

        const txn = await prisma.transaction.create({
          data: {
            householdId: m.householdId,
            date,
            amountCents,
            description,
            type: "cc_payment",
            accountId: account.id,
            creditCardId: card.id,
            ccCycleDue: body.cycleDue || null,
            isAutoGenerated: false,
            createdById: session.userId,
          },
          include: {
            account: { select: { id: true, name: true, icon: true } },
            creditCard: { select: { id: true, name: true, lastFour: true } },
          },
        });

        await logActivity({
          householdId: m.householdId,
          userId: session.userId,
          action: "create",
          entityType: "cc_payment",
          entityId: txn.id,
          summary: `Pago tarjeta ${card.name}: ${description}`,
        });

        return jsonOk({ transaction: txn }, 201);
      }
    );
  } catch (e) {
    return jsonError(e);
  }
}
