import { createHash, randomBytes } from "crypto";
import { prisma } from "@/lib/db";
import { AuthError, BadRequestError } from "@/lib/auth";
import { pesosToCents, todayISO } from "@/lib/utils";
import { logActivity } from "@/lib/household";
import { legacyFieldsFromFundings, type FundingInput } from "@/lib/transaction-funding";

const TOKEN_PREFIX = "mfmeat_";

export function hashMeatToken(token: string): string {
  return createHash("sha256").update(token.trim()).digest("hex");
}

export function generateMeatToken(): { token: string; hash: string; prefix: string } {
  const token = `${TOKEN_PREFIX}${randomBytes(24).toString("base64url")}`;
  return { token, hash: hashMeatToken(token), prefix: token.slice(0, 14) };
}

export function bearerToken(req: Request): string | null {
  const header = req.headers.get("authorization") || req.headers.get("Authorization");
  if (!header) return null;
  const match = header.match(/^Bearer\s+(.+)$/i);
  return match?.[1]?.trim() || null;
}

export async function requireMeatLink(req: Request) {
  const token = bearerToken(req);
  if (!token) throw new AuthError("Falta la llave de API");
  const link = await prisma.meatLink.findUnique({
    where: { tokenHash: hashMeatToken(token) },
    include: {
      household: { select: { id: true, name: true, currency: true, createdBy: true } },
      account: { select: { id: true, name: true, householdId: true } },
      creditCard: { select: { id: true, name: true, householdId: true } },
      category: { select: { id: true, name: true, type: true, householdId: true } },
    },
  });
  if (!link || !link.enabled) throw new AuthError("Llave inválida o desactivada");
  return link;
}

export function serializeMeatLink(
  link: {
    enabled: boolean;
    tokenPrefix: string;
    accountId: string | null;
    creditCardId: string | null;
    categoryId: string | null;
    lastUsedAt: Date | null;
    appUrl?: string | null;
  } | null
) {
  return {
    enabled: link?.enabled ?? false,
    hasToken: Boolean(link),
    tokenPrefix: link?.tokenPrefix ?? null,
    accountId: link?.accountId ?? null,
    creditCardId: link?.creditCardId ?? null,
    categoryId: link?.categoryId ?? null,
    lastUsedAt: link?.lastUsedAt?.toISOString() ?? null,
    appUrl: (link?.appUrl || "").trim(),
  };
}

export async function createMeatPurchase(opts: {
  link: Awaited<ReturnType<typeof requireMeatLink>>;
  amount: number | string;
  date?: string;
  description?: string;
  items?: { name: string; grams?: number }[];
}) {
  const amountCents = pesosToCents(opts.amount);
  if (amountCents <= 0) throw new BadRequestError("Monto inválido");

  const householdId = opts.link.householdId;
  let categoryId = opts.link.categoryId;
  if (categoryId && opts.link.category?.householdId !== householdId) categoryId = null;
  if (!categoryId) {
    const food = await prisma.category.findFirst({
      where: { householdId, type: "expense", name: "Alimentación" },
    });
    categoryId = food?.id ?? null;
  }

  let accountId =
    opts.link.accountId && opts.link.account?.householdId === householdId
      ? opts.link.accountId
      : null;
  let creditCardId =
    opts.link.creditCardId && opts.link.creditCard?.householdId === householdId
      ? opts.link.creditCardId
      : null;
  if (accountId && creditCardId) creditCardId = null;

  const names = (opts.items ?? [])
    .map((item) => item.name.trim())
    .filter(Boolean)
    .slice(0, 8);
  const extra = names.length ? ` · ${names.join(", ")}` : "";
  const description = (
    opts.description?.trim() || `Compra Meat${extra}`
  ).slice(0, 240);

  const fundings: FundingInput[] = [];
  if (creditCardId) {
    fundings.push({ amountCents, accountId: null, creditCardId });
  } else if (accountId) {
    fundings.push({ amountCents, accountId, creditCardId: null });
  }
  const legacy = legacyFieldsFromFundings(fundings);

  const ownerId =
    opts.link.household.createdBy ??
    (
      await prisma.membership.findFirst({
        where: { householdId, role: "owner" },
        select: { userId: true },
      })
    )?.userId ??
    null;

  const txn = await prisma.transaction.create({
    data: {
      householdId,
      date: opts.date && /^\d{4}-\d{2}-\d{2}$/.test(opts.date) ? opts.date : todayISO(),
      amountCents,
      description,
      type: "expense",
      categoryId,
      accountId: legacy.accountId,
      creditCardId: legacy.creditCardId,
      isAutoGenerated: true,
      createdById: ownerId,
      spentById: null,
    },
  });

  if (fundings.length > 0) {
    await prisma.transactionFunding.createMany({
      data: fundings.map((f) => ({
        transactionId: txn.id,
        amountCents: f.amountCents,
        accountId: f.accountId || null,
        creditCardId: f.creditCardId || null,
      })),
    });
  }

  await prisma.meatLink.update({
    where: { id: opts.link.id },
    data: { lastUsedAt: new Date() },
  });

  await logActivity({
    householdId,
    userId: ownerId ?? undefined,
    action: "create",
    entityType: "transaction",
    entityId: txn.id,
    summary: `Gasto desde Meat: ${description}`,
  });

  return txn;
}
